version: '3.3'

services:
  bwdc:
    container_name: bitwarden-bwdc
    image: bitwarden/directory-connector:2.9.8-containerise_v1.1
    volumes:
      - ./data/bwdc-profiles:/data/bwdc-profiles
    environment:
      - LOCAL_UID=1000
      - LOCAL_GID=1000
    #   - BITWARDENCLI_CONNECTOR_APPDATA_DIR='/bwdc-profiles/syncprofile_1'
    #   - BITWARDENCLI_CONNECTOR_PLAINTEXT_SECRETS=true
    #   - BITWARDENCLI_CONNECTOR_DEBUG=true
    #   - BW_QUIET
    #   - BW_RESPONSE
    #   - BW_CLEANEXIT
    #   - BW_PRETTY
    #   - BW_RAW
    #   - BW_NOINTERACTION
    #   - BW_CLIENTID
    #   - BW_CLIENTSECRET
    #   - BWCLI_ENV
    #   - BWDC_PROFILES_DIR
    #   - BWDC_SYNC_PARALLEL_MAX
    #   - BWDC_SYNC_INTERVAL_MIN
    #   - BWDC_SCAN_SLEEP_DUR
    #   - BWDC_CONF__syncprofile_1__BW_CLIENTID=VALUE
    #   - BWDC_CONF__syncprofile_1__BW_CLIENTSECRET=VALUE
