version: "3.9"

services:
  open-ldap:
    image: osixia/openldap:1.5.0
    command: --copy-service
    environment:
      LDAP_ORGANISATION: "Bitwarden"
      LDAP_DOMAIN: "bitwarden.com"
    volumes:
      - ./directory.ldif:/container/service/slapd/assets/config/bootstrap/ldif/output.ldif
    ports:
      - "389:389"
      - "636:636"
